# Generated by Django 4.2.7 on 2023-11-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
