# Generated by Django 4.2.5 on 2023-10-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comparer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="playlists/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="artwork",
            field=models.ImageField(blank=True, null=True, upload_to="artworks/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="playlist",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="songs", to="comparer.playlist"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="song_file",
            field=models.FileField(blank=True, null=True, upload_to="songs/"),
        ),
    ]
