# Generated by Django 4.2.7 on 2023-11-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0002_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
