# Generated by Django 4.2.5 on 2023-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0002_alter_playlist_image_alter_song_artwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(related_name='songs', to='comparer.playlist'),
        ),
    ]
