# Generated by Django 4.2.7 on 2023-12-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0003_remove_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
